audio_extract={toolsLocation}yt-dlp -f bestaudio -x --audio-format m4a --audio-quality 128K --embed-metadata --embed-thumbnail --convert-thumbnails jpg "https://www.youtube.com/watch?v={videoId}"
convert_to_m4a={toolsLocation}ffmpeg -i "{inputFile}" -ss 0 -c:a aac -b:a 128k -ar 44100 -ac 2 -c:v copy -disposition:v:0 attached_pic -movflags +faststart "{outputFile}"
audio_split={toolsLocation}ffmpeg {startArgs} {endArgs} -i "{inputFile}" -map 0:a:0 -vn {codecOptions} -map_metadata 0 -map_chapters 0 {formatOptions} -y "{outputFile}"
video_extract={toolsLocation}yt-dlp -f "bestvideo+bestaudio/best" -o "%(id)s.%(ext)s" "https://www.youtube.com/watch?v={videoId}"
video_resize={toolsLocation}ffmpeg -i "{inputFile}" -vf "scale=-2:480:force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2" -c:v libx264 -preset medium -crf 27 -c:a aac -b:a 96k -movflags +faststart "{outputFile}"
video_resize_fragment={toolsLocation}ffmpeg -ss {startTime} -to {endTime} -i "{inputFile}" -vf "scale=-2:480:force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2" -c:v libx264 -preset medium -crf 27 -c:a aac -b:a 96k -movflags +faststart "{outputFile}"
video_split={toolsLocation}ffmpeg {startArgs} {endArgs} -i "{inputFile}" {videoFilterArgs} {codecOptions} -map_metadata 0 -map_chapters 0 -f mp4 -y "{outputFile}"
server.port=8080
tools_location=${user.home}/pssm-music-playlist-tools
mediafiles_dir=${user.home}/media-files
default_audio_format=m4a
default_video_format=mp4
